#! /bin/zsh

set -e

TARGET="$1"

if [ -z "$TARGET" ]
then
	echo "usage: $0 <file or dir>"
	exit 1
fi

if [ "$(basename "$0")" = "mark-watched" ]
then
	POSITION="1.0"
elif [ "$(basename "$0")" = "mark-watched" ]
then
	POSITION="0.0"
else
	echo "Unrknown command: $0"
	exit 1
fi

if [ -d "$TARGET" ]
then
	cd "$TARGET"
	mkdir -p ".fabella/state/"
	for F in *(.)
	do
		echo "Marking $F"
		echo "$POSITION" > ".fabella/state/$F"
	done
	exit 0
fi

if [ -f "$TARGET" ]
then
	echo "Marking $TARGET"
	D="$(dirname "$TARGET")"
	F="$(basename "$TARGET")"
	mkdir -p "$D/.fabella/state"
	echo "$POSITION" > "$D/.fabella/state/$F"
	exit 0
fi

echo "Problem understanding $TARGET"
exit 1
